# Generated by Django 6.0.1 on 2026-01-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', '已发布'), ('draft', '草稿'), ('pending', '待审核')], default='draft', max_length=10, verbose_name='状态'),
        ),
    ]
